### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by stcev** [ankane/chartkick.py#1]
I've followed all the instructions to set up with Django. Despite this I cannot see the graphs, it only displays Loading...

To test, I tried to replicate the example graphs with the code in the readme, still stuck on loading.

This is happening using version 1.0 of chartkick and django 4.1.5

**Comment by ankane** [comment]
Hey @stcev, this likely means the JavaScript library isn't being loaded. Make sure it's included on any pages with charts.

```django
{% load static %}

<script src="{% static 'chartkick/Chart.bundle.js' %}"></script>
<script src="{% static 'chartkick/chartkick.js' %}"></script>
```

**Comment by stcev** [comment]
Hello @ankane. Thanks for your reply.

I have included the scripts in the pages, I have also added chartkick to the installed apps in Django (followed the steps detailed in the django usage guide) but still no luck.

**Comment by stcev** [comment]
Reopening this as the issue is not closed.

**Comment by ankane** [comment]
A few things to check with Developer Tools in your browser:

1. Are the files being loaded (and returning 200) in the Network tab?
2. Is `Chartkick` defined in the JavaScript console?
