### ISSUE TITLE
Passing options to the chart

### ISSUE THREAD

**Issue by gelie** [ankane/chartkick.py#2]
How do I pass options to a chart eg hoverOffset, padding, etc??

```
data = {"Blueberry": 44, "Strawberry": 23, "Dates": 33}
options = {"hoverOffset": 30}
chart = PieChart(data=data, options=options)
```

I have this basic example and want to add the hover effect. I tried the value as a string and as a number. It does not produce an error, nor does it provide any effect!!

**Comment by ankane** [comment]
Hi @gelie, use the `library` or `dataset` option to pass options specific to the charting library.
